input.onButtonPressed(Button.A, function () {
    music.playTone(659, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(523, music.beat(BeatFraction.Eighth))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Half))
    basic.pause(200)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(523, music.beat(BeatFraction.Half))
    basic.pause(100)
    music.playTone(392, music.beat(BeatFraction.Half))
    basic.pause(100)
    music.playTone(330, music.beat(BeatFraction.Half))
    basic.pause(100)
    music.playTone(440, music.beat(BeatFraction.Half))
    basic.pause(100)
    music.playTone(494, music.beat(BeatFraction.Eighth))
    basic.pause(100)
    music.playTone(466, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Half))
})
basic.forever(function () {
	
})
